# Requires Settings App Integation with User/Organization: https://probot.github.io/apps/settings/
repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  name: repo-template
  description: A repository template preconfigured with all the awesome bells and whistles
  homepage: https://github.com/theaccordance/repo-template
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_forking: true
  is_template: true
  delete_branch_on_merge: true
  allow_update_branch: true
  squash_merge_commit_titlestring: PR_TITLE
  squash_merge_commit_message: PR_BODY

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
  - name: first-timers-only
    # include the old name to rename and existing label
    oldname: Help Wanted

# Collaborators: give specific users access to this repository.
collaborators:
#  - username: bkeepers
    # Note: Only valid on organization-owned repositories.
    # The permission to grant the collaborator. Can be one of:
    # * `pull` - can pull, but not push to or administer this repository.
    # * `push` - can pull and push, but not administer this repository.
    # * `admin` - can pull, push and administer this repository.
#    permission: push

#  - username: hubot
#    permission: pull

#  - username:
#    permission: pull
